spring.application.name=CivisLocalTrack-Cameroon

spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# spring.sql.init.schema-locations=classpath:data.sql

minio.endpoint=http://localhost:9000
minio.access-key=minio
minio.secret-key=minio123
minio.bucket-name=budgetary-documents
