spring.application.name=CivisLocalTrack-Cameroon

spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

minio.endpoint=http://localhost:9000
minio.access-key=minio
minio.secret-key=minio123
minio.bucket-name=budgetary-documents

# spring.sql.init.schema-locations=classpath:data.sql

#Configuration de l'application pour qu'elle utilise Minio et pas AWS S3
aws.s3.bucketName=documents-budgetaires # Remplacez par le nom de votre bucket
aws.s3.endpoint=http://localhost:9000  # URL de MinIO
aws.s3.accessKey=minio                 # Clé d'accès MinIO
aws.s3.secretKey=passwordMinio123      # Clé secrète MinIO
aws.s3.region=us-east-1                # Région (peut être n'importe quelle valeur pour MinIO)


